[package]
org = "ballerina"
name = "task"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["task", "job", "schedule"]
repository = "https://github.com/ballerina-platform/module-ballerina-task"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "task-native"
version = "@toml.version@"
path = "../native/build/libs/task-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "./lib/quartz-@quartz.version@.jar"
