[package]
org = "ballerina"
name = "task"
version = "2.5.1"
authors = ["Ballerina"]
keywords = ["task", "job", "schedule"]
repository = "https://github.com/ballerina-platform/module-ballerina-task"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "task-native"
version = "2.5.1"
path = "../native/build/libs/task-native-2.5.1-SNAPSHOT.jar"

[[platform.java17.dependency]]
path = "./lib/quartz-2.3.2.jar"
